#!/usr/bin/env python3
"""LoRA supervised fine-tune for the Claw bundled model (WS-H).

Trains a small code model to emit Claw's Def-JSON protocol using only
in-scope symbols — the cold-start seed. The corpus (corpus.jsonl) is
generated by `claw corpus gen --stdlib`; every example references only
real symbols, so the model never learns a hallucination.

Run on a GPU (RunPod etc.):
    pip install -r requirements.txt
    python train.py --model Qwen/Qwen2.5-Coder-0.5B-Instruct --epochs 3

Outputs a LoRA adapter to ./claw-lora.
"""
import argparse, json, os
from datasets import Dataset
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import LoraConfig
from trl import SFTTrainer, SFTConfig

# The output protocol the benchmark runner sends at eval time. Training with
# the same framing the model will see at inference keeps train/eval aligned.
PROTOCOL = """Output ONLY a JSON array of definitions, no prose, no code fences.
Definition schema: {"name": str, "expr": <Expr>, "ty": <Type>, "effects": [<str>], "deprecated": false, "doc": ""}
Expr: {"Var": name} | {"Lit": {"Int": n}} | {"Lit": {"Str": s}} | {"Lam": {"params": ["p0"], "body": <Expr>}} | {"App": {"func": <Expr>, "args": [<Expr>]}}
Type: {"Named": "Nat"} | {"Var": "a"} | {"App": ["Result", [<Type>]]} | {"Fn": [[<Type>], <Type>]}
Lambda parameters MUST be named p0, p1, ... Reference a parameter or an in-scope symbol with {"Var": "<name>"}. Do NOT invent any other name.
"effects" lists the effect row: the union of the effect rows of every effectful in-scope symbol the code uses (e.g. ["Fs"] when calling File.read!); [] for pure code.
When defining MULTIPLE definitions, name helpers from the pool: step, helper, aux, go, part — a sibling may then be referenced with {"Var": "<helper name>"}."""


def build_text(tok, prompt, completion):
    """Chat-format one training example as prompt+protocol -> completion."""
    user = f"{prompt}\n\n{PROTOCOL}"
    msgs = [
        {"role": "user", "content": user},
        {"role": "assistant", "content": completion},
    ]
    return tok.apply_chat_template(msgs, tokenize=False)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="Qwen/Qwen2.5-Coder-0.5B-Instruct")
    ap.add_argument("--corpus", default="corpus-v3.jsonl")
    ap.add_argument("--out", default="claw-lora")
    ap.add_argument("--epochs", type=float, default=3.0)
    ap.add_argument("--lr", type=float, default=2e-4)
    ap.add_argument("--batch", type=int, default=8)
    args = ap.parse_args()

    tok = AutoTokenizer.from_pretrained(args.model)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token

    rows = [json.loads(l) for l in open(args.corpus) if l.strip()]
    texts = [build_text(tok, r["prompt"], r["completion"]) for r in rows]
    ds = Dataset.from_dict({"text": texts})
    print(f"corpus: {len(ds)} examples")

    model = AutoModelForCausalLM.from_pretrained(args.model, torch_dtype="auto", device_map="auto")
    if os.environ.get("CLAW_GRAD_CKPT"):
        model.gradient_checkpointing_enable()
        model.enable_input_require_grads()

    lora = LoraConfig(
        r=16, lora_alpha=32, lora_dropout=0.05, bias="none", task_type="CAUSAL_LM",
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    )
    cfg = SFTConfig(
        output_dir=args.out, num_train_epochs=args.epochs, learning_rate=args.lr,
        per_device_train_batch_size=args.batch, gradient_accumulation_steps=2,
        logging_steps=10, save_strategy="epoch", bf16=True, max_seq_length=1024,
        report_to="none", dataset_text_field="text",
    )
    trainer = SFTTrainer(model=model, args=cfg, train_dataset=ds, peft_config=lora)
    trainer.train()
    trainer.save_model(args.out)
    tok.save_pretrained(args.out)
    print(f"saved LoRA adapter to {args.out}")


if __name__ == "__main__":
    main()
